version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"                  # dashboard
      - "--providers.docker=true"              # dynamic discovery
      - "--entrypoints.web.address=:80"        # HTTP entrypoint
    ports:
      - "80:80"
      - "8080:8080"                            # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net


networks:
  traefik-net:
    driver: bridge
